# Generated by Django 5.2.13 on 2026-04-17 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DFC', 'Defensa Central'), ('LD', 'Lateral Derecho'), ('LI', 'Lateral Izquierdo'), ('MC', 'Mediocentro'), ('MD', 'Medio Derecho'), ('MI', 'Medio Izquierdo'), ('ED', 'Extremo Derecho'), ('EI', 'Extremo Izquierdo'), ('DC', 'Delantero Central')], default='DC', max_length=3)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='core.equipo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to='core.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneos',
            field=models.ManyToManyField(related_name='equipos', to='core.torneo'),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.SmallIntegerField(default=0)),
                ('goles_visita', models.SmallIntegerField(default=0)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('equipo_local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_local', to='core.equipo')),
                ('equipo_visita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_visita', to='core.equipo')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='core.jornada')),
            ],
            options={
                'unique_together': {('equipo_local', 'equipo_visita', 'fecha')},
            },
        ),
    ]
