# Generated by Django 5.2.13 on 2026-05-07 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2026, 5, 7, 22, 37, 33, 569300, tzinfo=datetime.timezone.utc)),
        ),
    ]
