# Generated by Django 5.2.13 on 2026-04-22 05:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2026, 4, 21, 23, 31, 10, 233438)),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='core.torneo'),
        ),
    ]
