# Generated by Django 5.2.13 on 2026-04-22 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jornada_fecha_alter_jornada_torneo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2026, 4, 22, 9, 29, 59, 691696, tzinfo=datetime.timezone.utc)),
        ),
    ]
